//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkaratakBot.Resources.Insert {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InsertDialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InsertDialog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AkaratakBot.Resources.Insert.InsertDialog", typeof(InsertDialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad entry, please re-enter the value.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the property address .
        /// </summary>
        internal static string InsertFieldAddressText {
            get {
                return ResourceManager.GetString("InsertFieldAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Number of Bathrooms.
        /// </summary>
        internal static string InsertFieldBathroomCount {
            get {
                return ResourceManager.GetString("InsertFieldBathroomCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Number of Bedrooms.
        /// </summary>
        internal static string InsertFieldBedroomCount {
            get {
                return ResourceManager.GetString("InsertFieldBedroomCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select category details.
        /// </summary>
        internal static string InsertFieldCategoryType {
            get {
                return ResourceManager.GetString("InsertFieldCategoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country details.
        /// </summary>
        internal static string InsertFieldCountryCity {
            get {
                return ResourceManager.GetString("InsertFieldCountryCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Floor Count.
        /// </summary>
        internal static string InsertFieldFloorCount {
            get {
                return ResourceManager.GetString("InsertFieldFloorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property&apos;s Floor.
        /// </summary>
        internal static string InsertFieldFloorLevelCount {
            get {
                return ResourceManager.GetString("InsertFieldFloorLevelCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Exterior Details.
        /// </summary>
        internal static string InsertFieldGardenGarageChoice {
            get {
                return ResourceManager.GetString("InsertFieldGardenGarageChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the property Location.
        /// </summary>
        internal static string InsertFieldLocationLatLng {
            get {
                return ResourceManager.GetString("InsertFieldLocationLatLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra details for the property.
        /// </summary>
        internal static string InsertFieldOtherDetailsText {
            get {
                return ResourceManager.GetString("InsertFieldOtherDetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Property Photo.
        /// </summary>
        internal static string InsertFieldPhotoSelection {
            get {
                return ResourceManager.GetString("InsertFieldPhotoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property size.
        /// </summary>
        internal static string InsertFieldPropertySize {
            get {
                return ResourceManager.GetString("InsertFieldPropertySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale /Rent Price.
        /// </summary>
        internal static string InsertFieldSaleRentPriceCount {
            get {
                return ResourceManager.GetString("InsertFieldSaleRentPriceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property&apos;s Area Zip Code( if exists ).
        /// </summary>
        internal static string InsertFieldZipCodeText {
            get {
                return ResourceManager.GetString("InsertFieldZipCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Property&apos;s Address.
        /// </summary>
        internal static string InsertFormAddressTextDescription {
            get {
                return ResourceManager.GetString("InsertFormAddressTextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the property&apos;s number of bathrooms.
        /// </summary>
        internal static string InsertFormBathroomCountDescription {
            get {
                return ResourceManager.GetString("InsertFormBathroomCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the property&apos;s number of bedrooms.
        /// </summary>
        internal static string InsertFormBedroomCountDescription {
            get {
                return ResourceManager.GetString("InsertFormBedroomCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;&gt;.
        /// </summary>
        internal static string InsertFormCountryNext {
            get {
                return ResourceManager.GetString("InsertFormCountryNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the number of floors for the property.
        /// </summary>
        internal static string InsertFormFloorCountDescription {
            get {
                return ResourceManager.GetString("InsertFormFloorCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In which floor is the property( -1 is basment , 2 is secnd floor).
        /// </summary>
        internal static string InsertFormFloorLevelCountDescription {
            get {
                return ResourceManager.GetString("InsertFormFloorLevelCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an option to add a property.
        /// </summary>
        internal static string InsertFormHeader {
            get {
                return ResourceManager.GetString("InsertFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the address of the property to show avalable locations.
        /// </summary>
        internal static string InsertFormLocationLatLngDescription {
            get {
                return ResourceManager.GetString("InsertFormLocationLatLngDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the details about the property ( features).
        /// </summary>
        internal static string InsertFormOtherDetailsTextDescription {
            get {
                return ResourceManager.GetString("InsertFormOtherDetailsTextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload the Photos of the Property (4 Max).
        /// </summary>
        internal static string InsertFormPropertyPhotoDescription {
            get {
                return ResourceManager.GetString("InsertFormPropertyPhotoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Property Size in square meters.
        /// </summary>
        internal static string InsertFormPropertySizeDescription {
            get {
                return ResourceManager.GetString("InsertFormPropertySizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the rent Price?.
        /// </summary>
        internal static string InsertFormRentPriceCountDescription {
            get {
                return ResourceManager.GetString("InsertFormRentPriceCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the sale Price?.
        /// </summary>
        internal static string InsertFormSalePriceCountDescription {
            get {
                return ResourceManager.GetString("InsertFormSalePriceCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the Zip Code?.
        /// </summary>
        internal static string InsertFormZipCodeTextDescription {
            get {
                return ResourceManager.GetString("InsertFormZipCodeTextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does the Property come with a Garage?.
        /// </summary>
        internal static string InsertGarageSelection {
            get {
                return ResourceManager.GetString("InsertGarageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does the Property come with a Garden?.
        /// </summary>
        internal static string InsertGardenSelection {
            get {
                return ResourceManager.GetString("InsertGardenSelection", resourceCulture);
            }
        }
    }
}
