//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkaratakBot.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract_Type
    {
        public int Contract_Type_ID { get; set; }
        public string Contract_Type_Desc { get; set; }
    }
}
