//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkaratakBot.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AkaratakModel : DbContext
    {
        public AkaratakModel()
            : base("name=AkaratakModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Contract_Type> Contract_Type { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<Property_Category> Property_Category { get; set; }
        public virtual DbSet<Property_Type> Property_Type { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<TestTable> TestTables { get; set; }
        public virtual DbSet<Property_Photos> Property_Photos { get; set; }
    }
}
