
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AkaratakBot.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class Property_Type
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Property_Type()
    {

        this.Properties = new HashSet<Property>();

    }


    public int Property_Type_ID { get; set; }

    public string Property_Type_Description { get; set; }

    public string Property_Type_Name { get; set; }

    public int Cat_ID { get; set; }



    public virtual Property_Category Property_Category { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Property> Properties { get; set; }

}

}
