//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkaratakBot.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property_Photos
    {
        public int Property_Photo_ID { get; set; }
        public int Property_ID { get; set; }
        public string Photo_Description { get; set; }
        public string Public_Id { get; set; }
        public string Photo_Url { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
