//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkaratakBot.Resources.Search {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SearchDialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SearchDialog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AkaratakBot.Resources.Search.SearchDialog", typeof(SearchDialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        internal static string SearchBoth {
            get {
                return ResourceManager.GetString("SearchBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a category to continue.
        /// </summary>
        internal static string SearchCategorySelection {
            get {
                return ResourceManager.GetString("SearchCategorySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue search?.
        /// </summary>
        internal static string SearchContinue {
            get {
                return ResourceManager.GetString("SearchContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no result with the specified filter.
        /// </summary>
        internal static string SearchEmptyResult {
            get {
                return ResourceManager.GetString("SearchEmptyResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Properties with Garage?.
        /// </summary>
        internal static string SearchGarageSelection {
            get {
                return ResourceManager.GetString("SearchGarageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Properties with Gardens?.
        /// </summary>
        internal static string SearchGardenSelection {
            get {
                return ResourceManager.GetString("SearchGardenSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No .
        /// </summary>
        internal static string SearchNo {
            get {
                return ResourceManager.GetString("SearchNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to what is the property type?.
        /// </summary>
        internal static string SearchTypeSelection {
            get {
                return ResourceManager.GetString("SearchTypeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        internal static string SearchViewDetails {
            get {
                return ResourceManager.GetString("SearchViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string SearchYes {
            get {
                return ResourceManager.GetString("SearchYes", resourceCulture);
            }
        }
    }
}
